<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE tasks [
<!ELEMENT tasks (project*)>
<!ELEMENT project (project_id,project_name,description,is_public,statuses,task*)>
<!ELEMENT project_id (#PCDATA)>
<!ELEMENT project_name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT is_public (#PCDATA)>
<!ELEMENT statuses (status+)>
<!ELEMENT status EMPTY>
<!ELEMENT task (task_id,summary,detail,percent_complete,priority,hours,start_date,end_date,creator,status_id,dependencies,assignees,history_entries)>
<!ELEMENT task_id (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT detail (#PCDATA)>
<!ELEMENT percent_complete (#PCDATA)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT hours (#PCDATA)>
<!ELEMENT start_date (#PCDATA)>
<!ELEMENT end_date (#PCDATA)>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT status_id (#PCDATA)>
<!ELEMENT dependencies (dependent_on*,dependent_of*)>
<!ELEMENT dependent_on (#PCDATA)>
<!ELEMENT dependent_of (#PCDATA)>
<!ELEMENT assignees (assignee*)>
<!ELEMENT assignee (#PCDATA)>
<!ELEMENT history_entries (history_entry*)>
<!ELEMENT history_entry (task_id, field_name, old_value, updator, date)>
<!ELEMENT field_name (#PCDATA)>
<!ELEMENT old_value (#PCDATA)>
<!ELEMENT updator (#PCDATA)>
<!ELEMENT date (#PCDATA)>

<!ATTLIST status id CDATA #REQUIRED>
<!ATTLIST status name CDATA #REQUIRED>
]>
<tasks>
<project>
<project_id>21720</project_id>
<project_name>host catcher</project_name>
<description>integrate a system which allows GPU to query host catchers</description>
<is_public>Yes</is_public>
<statuses>
<status id="1" name="Open" />
<status id="2" name="Closed" />
<status id="3" name="Deleted" />
<status id="100" name="None" />
</statuses>
</project>
<project>
<project_id>21721</project_id>
<project_name>GPU file upload</project_name>
<description>GPU has to implement something similar than a webserver for file upload</description>
<is_public>Yes</is_public>
<statuses>
<status id="1" name="Open" />
<status id="2" name="Closed" />
<status id="3" name="Deleted" />
<status id="100" name="None" />
</statuses>
</project>
<project>
<project_id>21722</project_id>
<project_name>SQL distributed database</project_name>
<description>GPU could also send out SQL commands over the Gnutella network</description>
<is_public>Yes</is_public>
<statuses>
<status id="1" name="Open" />
<status id="2" name="Closed" />
<status id="3" name="Deleted" />
<status id="100" name="None" />
</statuses>
</project>
<project>
<project_id>21723</project_id>
<project_name>Extensions</project_name>
<description>GPU Plugins and Frontends</description>
<is_public>Yes</is_public>
<statuses>
<status id="1" name="Open" />
<status id="2" name="Closed" />
<status id="3" name="Deleted" />
<status id="100" name="None" />
</statuses>
<task>
<task_id>58846</task_id>
<summary>Golomb rulers plugin</summary>
<detail>Golomb rulers are used in radioastronomy. The search for the Golomb ruler with 24 marks is open.
I think it shouldn't be more than 3 sites of source code.

see also http://www.distributed.net/ogr/index.html.en for some explanation what golomb rulers are</detail>
<percent_complete>0</percent_complete>
<priority>3</priority>
<hours>0</hours>
<start_date>1027814400</start_date>
<end_date>1374969600</end_date>
<creator>dangermaus</creator>
<status_id>3</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>58846</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1047576557</date>
</history_entry>
<history_entry>
<task_id>58846</task_id>
<field_name>end_date</field_name>
<old_value>1027814400</old_value>
<updator>dangermaus</updator>
<date>1076793218</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>61260</task_id>
<summary>develop a plugin for golomb rulers</summary>
<detail>refer to the documentation for more details</detail>
<percent_complete>0</percent_complete>
<priority>5</priority>
<hours>0</hours>
<start_date>1030924800</start_date>
<end_date>1378080000</end_date>
<creator>dangermaus</creator>
<status_id>3</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>61260</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1047576588</date>
</history_entry>
<history_entry>
<task_id>61260</task_id>
<field_name>details</field_name>
<old_value>get from </old_value>
<updator>dangermaus</updator>
<date>1047576588</date>
</history_entry>
<history_entry>
<task_id>61260</task_id>
<field_name>end_date</field_name>
<old_value>1030924800</old_value>
<updator>dangermaus</updator>
<date>1076793324</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>73643</task_id>
<summary>Golomb rulers plugin</summary>
<detail>to get from www.distributed.net the source code for a plugin and translate into Delphi.</detail>
<percent_complete>0</percent_complete>
<priority>5</priority>
<hours>0</hours>
<start_date>1047513600</start_date>
<end_date>1363132800</end_date>
<creator>dangermaus</creator>
<status_id>1</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>73643</task_id>
<field_name>end_date</field_name>
<old_value>1047513600</old_value>
<updator>dangermaus</updator>
<date>1076793351</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>74418</task_id>
<summary>Lens plugin</summary>
<detail>A lens, to show how the Update method in a plugin works.</detail>
<percent_complete>0</percent_complete>
<priority>5</priority>
<hours>0</hours>
<start_date>1048550400</start_date>
<end_date>1364169600</end_date>
<creator>dangermaus</creator>
<status_id>1</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>74418</task_id>
<field_name>end_date</field_name>
<old_value>1048550400</old_value>
<updator>dangermaus</updator>
<date>1076793405</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>74515</task_id>
<summary>Little Green Man plugin</summary>
<detail>something like Seti@home would be nice. Just like the name, LGM, used for the first pulsars discovered. They thought in the beginning, the periodic signal could be an extra-terrestrial intelligence. However, it was a black hole with two jetstreams, spinnig around with constant period.</detail>
<percent_complete>0</percent_complete>
<priority>5</priority>
<hours>0</hours>
<start_date>1048636800</start_date>
<end_date>1364256000</end_date>
<creator>dangermaus</creator>
<status_id>1</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>74515</task_id>
<field_name>end_date</field_name>
<old_value>1048636800</old_value>
<updator>dangermaus</updator>
<date>1076793369</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>79621</task_id>
<summary>3D ants and cosmology</summary>
<detail>just an idea after reading &amp;quot;Self-Assembling Network structures in an Agent based model&amp;quot; by Frank Schweitzer</detail>
<percent_complete>0</percent_complete>
<priority>5</priority>
<hours>0</hours>
<start_date>1055462400</start_date>
<end_date>1371081600</end_date>
<creator>dangermaus</creator>
<status_id>1</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>79621</task_id>
<field_name>end_date</field_name>
<old_value>1055462400</old_value>
<updator>dangermaus</updator>
<date>1076793422</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>91944</task_id>
<summary>chess parallelism</summary>
<detail>add somehow chess parallelism</detail>
<percent_complete>10</percent_complete>
<priority>5</priority>
<hours>40</hours>
<start_date>1073692800</start_date>
<end_date>1357776000</end_date>
<creator>dangermaus</creator>
<status_id>1</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>dangermaus</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>91944</task_id>
<field_name>end_date</field_name>
<old_value>1073692800</old_value>
<updator>dangermaus</updator>
<date>1076793442</date>
</history_entry>
<history_entry>
<task_id>91944</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1089319952</date>
</history_entry>
<history_entry>
<task_id>91944</task_id>
<field_name>details</field_name>
<old_value>changed plugin/frontend couple to get back scores with 0.877</old_value>
<updator>dangermaus</updator>
<date>1089319952</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>92028</task_id>
<summary>Gnutella mapping system</summary>
<detail>a special status command should give back the following:

number of threads ready to compute on node, % first thread, % second thread, % third thread, list of IPs to which the node is connected.

With this info, it would be cool to create an OpenGL graph of the current Gnutella network</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>
<hours>10</hours>
<start_date>1073865600</start_date>
<end_date>1100217600</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>dangermaus</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>92028</task_id>
<field_name>hours</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1074602323</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>details</field_name>
<old_value>own IP number has to be attached as well. this would be a very cool plugin!</old_value>
<updator>dangermaus</updator>
<date>1074602324</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1074791243</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>details</field_name>
<old_value>gpustatus command implemented in 0.827</old_value>
<updator>dangermaus</updator>
<date>1074791243</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>percent_complete</field_name>
<old_value>30</old_value>
<updator>dangermaus</updator>
<date>1074955919</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>percent_complete</field_name>
<old_value>75</old_value>
<updator>dangermaus</updator>
<date>1074993938</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>hours</field_name>
<old_value>100</old_value>
<updator>dangermaus</updator>
<date>1074993938</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>details</field_name>
<old_value>I could use color maps, add connections to normal Gnutella clients. IPfromOutside implemented in 0.830</old_value>
<updator>dangermaus</updator>
<date>1074993938</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>percent_complete</field_name>
<old_value>90</old_value>
<updator>dangermaus</updator>
<date>1076319087</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>end_date</field_name>
<old_value>1073865600</old_value>
<updator>dangermaus</updator>
<date>1076332373</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1078836660</date>
</history_entry>
<history_entry>
<task_id>92028</task_id>
<field_name>percent_complete</field_name>
<old_value>95</old_value>
<updator>dangermaus</updator>
<date>1078836661</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>92221</task_id>
<summary>investigate how to remove threefold problem</summary>
<detail>threefold accepted by backend, but not by frontend</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>
<hours>3</hours>
<start_date>1074124800</start_date>
<end_date>1358208000</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>dangermaus</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>92221</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1074602256</date>
</history_entry>
<history_entry>
<task_id>92221</task_id>
<field_name>percent_complete</field_name>
<old_value>10</old_value>
<updator>dangermaus</updator>
<date>1074602256</date>
</history_entry>
<history_entry>
<task_id>92221</task_id>
<field_name>end_date</field_name>
<old_value>1074124800</old_value>
<updator>dangermaus</updator>
<date>1076793482</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>92965</task_id>
<summary>3D open GL plugin for Feynman-Kac</summary>
<detail>hope to get it finished for sunday...</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>
<hours>20</hours>
<start_date>1075161600</start_date>
<end_date>1104105600</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>dangermaus</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>92965</task_id>
<field_name>percent_complete</field_name>
<old_value>5</old_value>
<updator>dangermaus</updator>
<date>1075812804</date>
</history_entry>
<history_entry>
<task_id>92965</task_id>
<field_name>percent_complete</field_name>
<old_value>50</old_value>
<updator>dangermaus</updator>
<date>1076319060</date>
</history_entry>
<history_entry>
<task_id>92965</task_id>
<field_name>percent_complete</field_name>
<old_value>75</old_value>
<updator>dangermaus</updator>
<date>1076520933</date>
</history_entry>
<history_entry>
<task_id>92965</task_id>
<field_name>end_date</field_name>
<old_value>1075161600</old_value>
<updator>dangermaus</updator>
<date>1076793275</date>
</history_entry>
<history_entry>
<task_id>92965</task_id>
<field_name>percent_complete</field_name>
<old_value>85</old_value>
<updator>dangermaus</updator>
<date>1078836617</date>
</history_entry>
<history_entry>
<task_id>92965</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1078836690</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>93638</task_id>
<summary>Feynman Kac frontend</summary>
<detail>that plots results of Feynman Kac in 3D, errors as well</detail>
<percent_complete>100</percent_complete>
<priority>7</priority>
<hours>30</hours>
<start_date>1076284800</start_date>
<end_date>1362787200</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>dangermaus</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>93638</task_id>
<field_name>priority</field_name>
<old_value>5</old_value>
<updator>dangermaus</updator>
<date>1076332217</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1076520910</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>percent_complete</field_name>
<old_value>40</old_value>
<updator>dangermaus</updator>
<date>1076602449</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>details</field_name>
<old_value>still to do:
- verify problems at boundary with a=0.4 b=0.7 c=0.6
- add color map</old_value>
<updator>dangermaus</updator>
<date>1076602449</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>percent_complete</field_name>
<old_value>70</old_value>
<updator>dangermaus</updator>
<date>1087944435</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>details</field_name>
<old_value>heat color map implemented in libraries\colormap.pas</old_value>
<updator>dangermaus</updator>
<date>1087944435</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>end_date</field_name>
<old_value>1078790400</old_value>
<updator>dangermaus</updator>
<date>1087995655</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>percent_complete</field_name>
<old_value>75</old_value>
<updator>dangermaus</updator>
<date>1088096915</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>details</field_name>
<old_value>half of the color maps implemented...</old_value>
<updator>dangermaus</updator>
<date>1088096915</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1088193174</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>percent_complete</field_name>
<old_value>80</old_value>
<updator>dangermaus</updator>
<date>1088193174</date>
</history_entry>
<history_entry>
<task_id>93638</task_id>
<field_name>details</field_name>
<old_value>0.876: bug involving caption solved
now colors are correct.
All color maps added.
Improvements in speed of results.</old_value>
<updator>dangermaus</updator>
<date>1088193174</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>93639</task_id>
<summary>Corewars plugin</summary>
<detail>A plugin for Corewars, see http://corewars.sf.net</detail>
<percent_complete>15</percent_complete>
<priority>5</priority>
<hours>90</hours>
<start_date>1076284800</start_date>
<end_date>1360368000</end_date>
<creator>dangermaus</creator>
<status_id>1</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>93639</task_id>
<field_name>end_date</field_name>
<old_value>1076284800</old_value>
<updator>dangermaus</updator>
<date>1076793460</date>
</history_entry>
<history_entry>
<task_id>93639</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1101116948</date>
</history_entry>
<history_entry>
<task_id>93639</task_id>
<field_name>details</field_name>
<old_value>examples of code are here:
http://www.geocities.com/CapeCanaveral/Hall/2027/corewar.zip

idea of nanobit: do it in a evolutionary way,
so that programs improve over time</old_value>
<updator>dangermaus</updator>
<date>1101116949</date>
</history_entry>
<history_entry>
<task_id>93639</task_id>
<field_name>percent_complete</field_name>
<old_value>5</old_value>
<updator>dangermaus</updator>
<date>1101680703</date>
</history_entry>
<history_entry>
<task_id>93639</task_id>
<field_name>details</field_name>
<old_value>nanobit ported code to delphi.
evolutionary code also there.

original articles of Dewdney here:
http://www.koth.org/info/akdewdney/index.html</old_value>
<updator>dangermaus</updator>
<date>1101680703</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>93682</task_id>
<summary>verify Wes plugin</summary>
<detail>check for errors in ThrowNstonesintoMboxes</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>
<hours>4</hours>
<start_date>1076371200</start_date>
<end_date>1078876800</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>dangermaus</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>93682</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1076602489</date>
</history_entry>
<history_entry>
<task_id>93682</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1077194179</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>93700</task_id>
<summary>MDS for 3D Network Mapper</summary>
<detail>ask Stefan Kleiber how Multidimensional Scaling works to get better 3D graphs for the network mapper</detail>
<percent_complete>0</percent_complete>
<priority>5</priority>
<hours>30</hours>
<start_date>1076371200</start_date>
<end_date>1370822400</end_date>
<creator>dangermaus</creator>
<status_id>1</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>93700</task_id>
<field_name>end_date</field_name>
<old_value>1086825600</old_value>
<updator>dangermaus</updator>
<date>1087995623</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>94377</task_id>
<summary>Eliza - Racter plugin</summary>
<detail>a speaking computer plugin that answers chat a la Racter as described in Scientific American.
Would work fine as soon as strings can be sent to plugins!</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>
<hours>100</hours>
<start_date>1077494400</start_date>
<end_date>1361577600</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>94377</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1108567920</date>
</history_entry>
<history_entry>
<task_id>94377</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1108567920</date>
</history_entry>
<history_entry>
<task_id>94377</task_id>
<field_name>details</field_name>
<old_value>done by nanobit  with 0.9101 under dllbuilding/aibot</old_value>
<updator>dangermaus</updator>
<date>1108567920</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>95786</task_id>
<summary>node names for 3D Network Mapper</summary>
<detail>display  node names for 3DNM</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>
<hours>15</hours>
<start_date>1079654400</start_date>
<end_date>1385683200</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>95786</task_id>
<field_name>end_date</field_name>
<old_value>1079654400</old_value>
<updator>dangermaus</updator>
<date>1079711014</date>
</history_entry>
<history_entry>
<task_id>95786</task_id>
<field_name>end_date</field_name>
<old_value>1080518400</old_value>
<updator>dangermaus</updator>
<date>1079711034</date>
</history_entry>
<history_entry>
<task_id>95786</task_id>
<field_name>end_date</field_name>
<old_value>1101686400</old_value>
<updator>dangermaus</updator>
<date>1101907904</date>
</history_entry>
<history_entry>
<task_id>95786</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1160999529</date>
</history_entry>
<history_entry>
<task_id>95786</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1160999529</date>
</history_entry>
<history_entry>
<task_id>95786</task_id>
<field_name>details</field_name>
<old_value>added with 0.9361.</old_value>
<updator>dangermaus</updator>
<date>1160999529</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>96986</task_id>
<summary>Interface to Globus Toolkit</summary>
<detail>think a little how to interface GPU to the Globus Toolkit services offered on port 8090.</detail>
<percent_complete>0</percent_complete>
<priority>5</priority>
<hours>100</hours>
<start_date>1081468800</start_date>
<end_date>1302307200</end_date>
<creator>dangermaus</creator>
<status_id>1</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
</history_entries>
</task>
<task>
<task_id>98293</task_id>
<summary>write plugin-frontend couple in C</summary>
<detail>to show that C and C++ can be used.</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>
<hours>20</hours>
<start_date>1083715200</start_date>
<end_date>1367712000</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>98293</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1131027821</date>
</history_entry>
<history_entry>
<task_id>98293</task_id>
<field_name>details</field_name>
<old_value>plugin is now written in Dev-C++, see gpu_simple_c_plugin.dll under /src/dllbuilding/c_example.</old_value>
<updator>dangermaus</updator>
<date>1131027821</date>
</history_entry>
<history_entry>
<task_id>98293</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1135369909</date>
</history_entry>
<history_entry>
<task_id>98293</task_id>
<field_name>percent_complete</field_name>
<old_value>50</old_value>
<updator>dangermaus</updator>
<date>1135369909</date>
</history_entry>
<history_entry>
<task_id>98293</task_id>
<field_name>details</field_name>
<old_value>done, C++ frontend was written by Edgar Sartori. code is on cvs under /src/frontend/simplest_c_example</old_value>
<updator>dangermaus</updator>
<date>1135369909</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>98552</task_id>
<summary>bug - autoupdate does not shutdown GPU</summary>
<detail>if another delphi program with the name TMainForm is running, autoupdate and trigger are not able to shutdown the program.</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>
<hours>2</hours>
<start_date>1084060800</start_date>
<end_date>1368057600</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>98552</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1084353809</date>
</history_entry>
<history_entry>
<task_id>98552</task_id>
<field_name>details</field_name>
<old_value>changed form name from TMainForm to GPUTella</old_value>
<updator>dangermaus</updator>
<date>1084353809</date>
</history_entry>
<history_entry>
<task_id>98552</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1084899988</date>
</history_entry>
<history_entry>
<task_id>98552</task_id>
<field_name>percent_complete</field_name>
<old_value>70</old_value>
<updator>dangermaus</updator>
<date>1084899988</date>
</history_entry>
<history_entry>
<task_id>98552</task_id>
<field_name>details</field_name>
<old_value>ok it works.</old_value>
<updator>dangermaus</updator>
<date>1084899988</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>98906</task_id>
<summary>move chess to string parameters</summary>
<detail>move chess to string parameters</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>
<hours>3</hours>
<start_date>1084579200</start_date>
<end_date>1368576000</end_date>
<creator>dangermaus</creator>
<status_id>2</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>98906</task_id>
<field_name>status_id</field_name>
<old_value>1</old_value>
<updator>dangermaus</updator>
<date>1086211496</date>
</history_entry>
<history_entry>
<task_id>98906</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1086211496</date>
</history_entry>
<history_entry>
<task_id>98906</task_id>
<field_name>details</field_name>
<old_value>done with 0.868</old_value>
<updator>dangermaus</updator>
<date>1086211496</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>98907</task_id>
<summary>compute electromagnetic field of dipoles</summary>
<detail>compute electromagnetic field of dipoles, of many of them. see if result might be similar to gravity.</detail>
<percent_complete>5</percent_complete>
<priority>5</priority>
<hours>140</hours>
<start_date>1084579200</start_date>
<end_date>1368576000</end_date>
<creator>dangermaus</creator>
<status_id>1</status_id>
<dependencies>
<dependent_on>100</dependent_on>
</dependencies>
<assignees>
<assignee>nobody</assignee>
</assignees>
<history_entries>
<history_entry>
<task_id>98907</task_id>
<field_name>end_date</field_name>
<old_value>1084579200</old_value>
<updator>dangermaus</updator>
<date>1084648005</date>
</history_entry>
<history_entry>
<task_id>98907</task_id>
<field_name>percent_complete</field_name>
<old_value>0</old_value>
<updator>dangermaus</updator>
<date>1167214029</date>
</history_entry>
<history_entry>
<task_id>98907</task_id>
<field_name>details</field_name>
<old_value>This is an interesting paper:
Free Fall of Elementary Particles
http://www.electrogravityphysics.com/html/contents.html
by Nils Rognerud</old_value>
<updator>dangermaus</updator>
<date>1167214029</date>
</history_entry>
<history_entry>
<task_id>98907</task_id>
<field_name>details</field_name>
<old_value>my father sent me some interesting code to  look at</old_value>
<updator>dangermaus</updator>
<date>1169413288</date>
</history_entry>
</history_entries>
</task>
<task>
<task_id>99349</task_id>
<summary>hour synchronization for GPUs</summary>
<detail>synchronize all GPUs on the same hour, use mean value of all clocks.</detail>
<percent_complete>100</percent_complete>
<priority>5</priority>